import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { applyLiveNarrative } from "../../lib/live-narrative";
import type { CoachingReport } from "../../../shared/types";

function baseReport(): CoachingReport {
  return {
    driver_id: "test-driver",
    corners: [
      {
        name: "Sector 1 corner",
        sector: 1,
        current_delta_s: 0.34,
        recommendation: "FIXTURE expert prose for sector 1.",
        recommendation_beginner: "FIXTURE beginner prose for sector 1.",
        citations: [{ fia_article: "Appendix L", coa_section: "Adaptive-equipment provisions" }],
      },
      {
        name: "Sector 2 corner",
        sector: 2,
        current_delta_s: 0.08,
        recommendation: "FIXTURE expert prose for sector 2.",
        recommendation_beginner: "FIXTURE beginner prose for sector 2.",
        citations: [{ fia_article: "Appendix L", coa_section: "Adaptive-equipment provisions" }],
      },
    ],
    tuning_delta: {
      parameter: "primary_actuation_modulation_pct",
      current: 100,
      recommended: 90,
      unit: "pct",
      citation: { fia_article: "Appendix L", coa_section: "Adaptive-equipment provisions" },
    },
    forecast: [{ sector_idx: 0, mean: 47.42, low: 47.21, high: 47.66 }],
    audit: { verdict: "approve", reasoning_trace: ["ok"], audit_id: "abc123" },
    provenance: {
      model_versions: {
        granite_docling: "ibm-granite/granite-docling-258m",
        granite_vision: "ibm-granite/granite-vision-4.1-4b",
        granite_ttm: "ibm-granite/granite-timeseries-ttm-r2",
        granite_instruct: "ibm-granite/granite-4.1-8b-instruct",
        granite_guardian: "ibm-granite/granite-guardian-4.1-8b",
      },
      commit_sha: "0000000000000000000000000000000000000000",
      generated_at_iso: "2026-05-30T00:00:00.000Z",
    },
  };
}

function stubFetch(impl: () => Promise<Response> | Response): void {
  vi.stubGlobal("fetch", vi.fn(impl));
}

function jsonResponse(payload: unknown, ok = true, status = 200): Response {
  return {
    ok,
    status,
    json: async () => payload,
  } as unknown as Response;
}

describe("applyLiveNarrative wave-64 merge helper", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });
  afterEach(() => {
    vi.unstubAllGlobals();
    vi.restoreAllMocks();
  });

  it("labels the report 'fixture' and leaves prose untouched when the route returns ok:false", async () => {
    stubFetch(() => jsonResponse({ ok: false, source: "stub" }));
    const result = await applyLiveNarrative(baseReport(), "my debrief");
    expect(result.narrative_source).toBe("fixture");
    expect(result.corners[0].recommendation).toBe("FIXTURE expert prose for sector 1.");
    // Numbers + citations preserved.
    expect(result.corners[0].current_delta_s).toBe(0.34);
    expect(result.tuning_delta.recommended).toBe(90);
  });

  it("merges live prose and labels 'granite-live' on ok:true, keeping numbers + citations", async () => {
    stubFetch(() =>
      jsonResponse({
        ok: true,
        source: "granite-live",
        corners: [
          {
            name: "Sector 1 corner",
            recommendation: "LIVE expert prose for sector 1.",
            recommendation_beginner: "LIVE beginner prose for sector 1.",
            reasoning_chain: [{ step: "cause", label: "Why", content: "LIVE reasoning." }],
          },
          {
            name: "Sector 2 corner",
            recommendation: "LIVE expert prose for sector 2.",
            recommendation_beginner: "LIVE beginner prose for sector 2.",
            reasoning_chain: [],
          },
        ],
        summary: "live summary",
      }),
    );
    const result = await applyLiveNarrative(baseReport(), "my debrief");
    expect(result.narrative_source).toBe("granite-live");
    expect(result.corners[0].recommendation).toBe("LIVE expert prose for sector 1.");
    expect(result.corners[0].recommendation_beginner).toBe("LIVE beginner prose for sector 1.");
    expect(result.corners[0].reasoning_chain?.[0]?.content).toBe("LIVE reasoning.");
    // Numbers + citations are NOT regenerated by the model.
    expect(result.corners[0].current_delta_s).toBe(0.34);
    expect(result.corners[0].citations[0].fia_article).toBe("Appendix L");
    expect(result.forecast[0].mean).toBe(47.42);
  });

  it("keeps base prose for a corner whose live recommendation is empty", async () => {
    stubFetch(() =>
      jsonResponse({
        ok: true,
        source: "granite-live",
        corners: [
          { name: "Sector 1 corner", recommendation: "LIVE sector 1.", recommendation_beginner: "b", reasoning_chain: [] },
          { name: "Sector 2 corner", recommendation: "   ", recommendation_beginner: "", reasoning_chain: [] },
        ],
        summary: "s",
      }),
    );
    const result = await applyLiveNarrative(baseReport(), "d");
    expect(result.corners[0].recommendation).toBe("LIVE sector 1.");
    expect(result.corners[1].recommendation).toBe("FIXTURE expert prose for sector 2.");
  });

  it("degrades to fixture when fetch rejects", async () => {
    stubFetch(() => Promise.reject(new Error("network down")));
    const result = await applyLiveNarrative(baseReport(), "d");
    expect(result.narrative_source).toBe("fixture");
    expect(result.corners[0].recommendation).toBe("FIXTURE expert prose for sector 1.");
  });

  it("degrades to fixture on a non-200 response", async () => {
    stubFetch(() => jsonResponse({ error: "boom" }, false, 500));
    const result = await applyLiveNarrative(baseReport(), "d");
    expect(result.narrative_source).toBe("fixture");
  });
});
